version: '3.1'

services:
  activity-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - ./activity:/var/lib/postgresql/data:rw # mounting the entire activity/ folder to /var/server
  activity-server:
    build: ./activity
    depends_on: ["activity-db"]
    ports:
      - "8000:8000"
    volumes:
      - ./activity:/var/server:rw
      - /var/server/node_modules
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app:rw
      - /app/node_modules
  flask-backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes: 
      - ./backend:/var/backend
  mongo-db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
