version: '3.1'

services:
  activity-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
  activity-server:
    build: ./activity
    depends_on: ["activity-db"]
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app:rw
      - /app/node_modules
  flask-backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes: 
      - ./backend:/var/backend
