version: '3.1'

services:
  activity-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw # mounting the entire activity/ folder to /var/server
  activity-server:
    build: ./activity
    depends_on: ["activity-db"]
    ports:
      - "8000:8000"
    volumes:
      - ./activity:/var/server:rw
      - /var/server/node_modules

volumes:
  postgres_data:
